### PR TITLE
Bug fixes / small features

### LINKED ISSUE #19: Add/Remove bot accepts non-bot/script tomls too
I accidentally added my `loadout.toml` instead of `beast.bot.toml`, but the gui did not complain, neither in console or toasts. For bots/scripts, the gui should insist on the `bot.toml` and `script.toml` postfixes.

### PR DESCRIPTION
**Pull request by VirxEC**
Requires #20 to be merged first

- Only allow bot.toml and script.toml files to be added - closes #19 
- Exclude human from search results
- Reload scripts - not just bots
- Disable flip animation on team bot lists when they have 16 players or more, because the animation was causing lag. Disabling it allows adding dozens of bots to either team without lag.
- Add new maps, NeoTokyo (Arcade) and Futura Garden
- Sort maps alphabetically, but all non-standard maps are still below all standard maps

  image

  image

- Sort mutators by name + new mutators + better mutator names

  image

- Refactor tags again to exactly match v4 + working favorites system for bots & scripts

  image

  New default state of the bot info modal's title:

  image

  When favorited:

  image

  image

- Update time remaining in the events calendar in real time. Previously, it mimicked the v4 GUI where it was set once upon launch and didn't update until the GUI was restarted.

  image

- Adaptive bot info modal content. The image is now vertically centered, and readjusts when the window is shrunk.

  image

  image

- New extra options for `AutoStartAgents` and `WaitForAgents` that default to `true`:

  image

- Make unique path segments viewable in the team bot lists

  image

### CODE REVIEW

File: frontend/src/components/BotList.svelte [hunk 1]
```diff
@@ -209,8 +224,10 @@ function handleDndFinalize(e: any) {
 function handleBotClick(bot: DraggablePlayer) {
   const newId = `${bot.id}-${Math.round(Math.random() * 100000)}`;
   const idx = filteredBots.findIndex((item) => item.id === bot.id);
-  //@ts-ignore
-  filteredBots.splice(idx, 1, { ...filteredBots[idx], id: newId });
+  if (idx !== -1) {
+    // @ts-ignore
+    filteredBots[idx] = { ...filteredBots[idx], id: newId };
+  }
```
Comment (VirxEC) [inline frontend/src/components/BotList.svelte:230]: i dont see why this would cause any bugs but its the only other thing touching the dnd logic

Comment (VirxEC) [reply frontend/src/components/BotList.svelte:230]: reverting doesn't fix

File: frontend/src/components/PathsViewer.svelte [hunk 2]
```diff
@@ -91,14 +91,20 @@ async function addFolder() {
...
-  }
-
-  addInstallPath(result);
+      addInstallPath(result);
+    })
+    .catch((error) => {
+      toast.error(
+        "Failed to add file: Only bot.toml or script.toml files are allowed",
+      );
+    });
```
Comment (NicEastvillage) [inline frontend/src/components/PathsViewer.svelte:107]: What happens on malformed tomls?

Comment (VirxEC) [reply frontend/src/components/PathsViewer.svelte:107]: they get added anyways but I think it is the right thing to do

Comment (swz-git) [reply frontend/src/components/PathsViewer.svelte:107]: This is what it looks like, but this isn't something that this pr introduced and is therefor imo kinda "out of scope".
image

Comment (VirxEC) [reply frontend/src/components/PathsViewer.svelte:107]: Not a bad idea, but where would this go? Only for add file? When loading/reloading the list of bots/scripts?

File: frontend/src/base-players.ts
Comment (swz-git) [inline frontend/src/base-players.ts:1]: why is uuid better than math.random?

**Review by swz-git — APPROVED** [review]
Nice work 👍🏻

File: frontend/src/base-players.ts
Comment (VirxEC) [reply frontend/src/base-players.ts:1]: For one, it's always a fixed-length string. Your old system took the old id, either number or string, generated a new big integer, and appended it to the end as if the 2 were strings. This is bad because if you have a lot of bots then the length of the ID will grow infinitely.

This system requires unique IDs for every item, so my first thought was UUIDs which are literally made for what we need.

According to <https://stackoverflow.com/a/2117523/10930209> where I got the UUID v4 implentation in JS from, using math.random is not a good idea:

> Note: The use of any UUID generator that relies on Math.random() is strongly discouraged (including snippets featured in previous versions of this answer) for [reasons best explained here](https://bocoup.com/blog/random-numbers). TL;DR: solutions based on Math.random() do not provide good uniqueness guarantees.

If you want, we can use the `uuidv4()` function from <https://www.npmjs.com/package/uuid> instead

File: frontend/src/components/PathsViewer.svelte (hunk 2 above)
Comment (VirxEC) [reply frontend/src/components/PathsViewer.svelte:107]: Also true, maybe we address this later

File: frontend/src/base-players.ts
Comment (swz-git) [reply frontend/src/base-players.ts:1]: this way is fine, just wanted to know the reason for the switch
